(function(){
  const storageKey='vish-project-created-purchase-orders';
  const defaultProducts={
    'PO-2050':'Circuit Breaker, Auxiliary Contact, Overload Relay',
    'PO-2049':'ABB Contactors, Auxiliary Relays',
    'PO-2048':'Pneumatic Cylinders, Cylinder Seal Kits',
    'PO-2047':'V-Belts, Timing Belts',
    'PO-2046':'Circulation Pumps, Pump Flange Kits',
    'PO-2045':'Air Filter Regulators, Pressure Gauges'
  };

  function readRecords(){
    try{const value=JSON.parse(localStorage.getItem(storageKey)||'[]');return Array.isArray(value)?value:[]}catch(e){return []}
  }
  function writeRecords(records){
    try{localStorage.setItem(storageKey,JSON.stringify(records))}catch(e){}
  }
  function clean(value){
    return String(value??'').normalize('NFKD').replace(/[^\x20-\x7E]/g,'').replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');
  }
  function numberFromMoney(value){return Number(String(value??0).replace(/[^0-9.-]/g,''))||0}
  function formatMoney(value){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(value)||0)}
  function displayDate(date){return date.toLocaleDateString('en-US',{month:'short',day:'2-digit',year:'numeric'})}
  function text(x,y,size,value,bold){return `BT /${bold?'F2':'F1'} ${size} Tf ${x} ${y} Td (${clean(value)}) Tj ET`}

  function buildPdf(po){
    const total=Number(po.total)||0;
    const quantity=Math.max(1,Number(po.quantity)||1);
    const unitPrice=Number(po.unitPrice)||total/quantity;
    const product=String(po.product||'Products').slice(0,72);
    const commands=[
      '0.075 0.255 0.19 rg 0 718 612 74 re f',
      '1 1 1 rg',
      text(42,755,18,'INVENTORY AUTOMATION',true),
      text(42,735,9,'Vish Plant | Procurement',false),
      text(418,754,18,'PURCHASE ORDER',true),
      text(472,734,10,po.poNumber,true),
      '0.09 0.13 0.11 rg',
      text(42,680,9,'SUPPLIER',true),text(42,662,13,po.supplier,true),
      text(330,680,9,'SHIP TO',true),text(330,662,13,'Vish Plant',true),
      text(42,620,9,'ORDER DATE',true),text(42,602,11,po.created,false),
      text(330,620,9,'REQUIRED BY',true),text(330,602,11,po.requiredBy,false),
      '0.075 0.255 0.19 rg 42 540 528 30 re f','1 1 1 rg',
      text(52,551,9,'PRODUCT / MATERIAL',true),text(330,551,9,'PART NUMBER',true),text(455,551,9,'QTY',true),text(510,551,9,'TOTAL',true),
      '0.09 0.13 0.11 rg',
      text(52,515,10,product,true),text(330,515,9,po.sku||'N/A',false),text(455,515,10,quantity,false),text(510,515,10,formatMoney(total),true),
      '0.82 0.86 0.83 RG 42 495 m 570 495 l S',
      text(405,458,10,'Unit price',false),text(510,458,10,formatMoney(unitPrice),false),
      '0.075 0.255 0.19 RG 405 442 m 570 442 l S',
      text(405,418,13,'ORDER TOTAL',true),text(510,418,13,formatMoney(total),true),
      text(42,360,10,'SUPPLIER INSTRUCTIONS',true),
      text(42,338,9,'Please confirm price, availability, quantity, and delivery date.',false),
      text(42,321,9,'Contact the buyer before shipment about any quality or delivery discrepancy.',false),
      text(42,278,9,'REQUESTED BY',true),text(42,260,11,'Vishwajith',false),
      '0.82 0.86 0.83 RG 42 90 m 570 90 l S',
      text(42,68,8,'Generated by Inventory Automation. Supplier confirmation requested.',false)
    ].join('\n');
    const objects=[
      '<< /Type /Catalog /Pages 2 0 R >>',
      '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
      '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> /Contents 4 0 R >>',
      `<< /Length ${new TextEncoder().encode(commands).length} >>\nstream\n${commands}\nendstream`,
      '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
      '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>'
    ];
    let pdf='%PDF-1.4\n';
    const offsets=[0];
    objects.forEach((object,index)=>{offsets.push(new TextEncoder().encode(pdf).length);pdf+=`${index+1} 0 obj\n${object}\nendobj\n`});
    const xref=new TextEncoder().encode(pdf).length;
    pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;
    offsets.slice(1).forEach(offset=>{pdf+=`${String(offset).padStart(10,'0')} 00000 n \n`});
    pdf+=`trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
    return pdf;
  }

  function savePdf(po){
    const blob=new Blob([buildPdf(po)],{type:'application/pdf'});
    const url=URL.createObjectURL(blob);
    const link=document.createElement('a');
    link.href=url;link.download=`${po.poNumber}-purchase-order.pdf`;
    document.body.appendChild(link);link.click();link.remove();
    setTimeout(()=>URL.revokeObjectURL(url),1500);
  }

  window.downloadPurchaseOrderPdfRecord=savePdf;
  window.downloadPurchaseOrderPdf=function(index){
    const order=orders[index];
    if(!order)return;
    const saved=readRecords().find(record=>record.poNumber===order[0]);
    if(saved){savePdf(saved);return}
    const quantity=Math.max(1,Number(order[4])||1);
    const total=numberFromMoney(order[5]);
    savePdf({poNumber:order[0],supplier:order[1],created:order[2],requiredBy:order[3],product:order[8]||defaultProducts[order[0]]||'General products',sku:'Multiple products',quantity,unitPrice:total/quantity,total});
  };

  function updateOrderMetrics(){
    const open=orders.filter(order=>!['received','critical'].includes(order[6])).length;
    const waiting=orders.filter(order=>order[6]==='pending').length;
    const dashboardCount=document.querySelector('#dashboard .metrics .metric:nth-child(3) h2');
    const waitingCount=document.querySelector('#orders .metrics .metric:first-child h2');
    if(dashboardCount)dashboardCount.textContent=open;
    if(waitingCount)waitingCount.textContent=waiting;
  }

  function clearAutomaticOrders(){
    const previousRecords=readRecords();
    const automaticNumbers=new Set(previousRecords.filter(record=>record.automatic).map(record=>record.poNumber));
    const manualRecords=previousRecords.filter(record=>!record.automatic);
    for(let index=orders.length-1;index>=0;index--){
      if(automaticNumbers.has(orders[index][0])||String(orders[index][0]).startsWith('AUTO-'))orders.splice(index,1);
    }
    try{
      const statuses=JSON.parse(localStorage.getItem('vish-project-order-statuses')||'{}');
      Object.keys(statuses).forEach(number=>{if(automaticNumbers.has(number)||number.startsWith('AUTO-'))delete statuses[number]});
      localStorage.setItem('vish-project-order-statuses',JSON.stringify(statuses));
    }catch(e){}
    writeRecords(manualRecords);
    return manualRecords;
  }

  // Each refresh starts with the normal manual-PO baseline. Clicking Automate POs
  // then makes the automatically generated shortage orders easy to demonstrate.
  clearAutomaticOrders();
  renderOrders();

  const button=document.querySelector('#automateReorderBtn');
  if(button)button.addEventListener('click',()=>{
    const records=clearAutomaticOrders();
    const lowStock=parts.filter(part=>part.stock<part.min);
    const now=new Date();now.setHours(12,0,0,0);
    const required=new Date(now);required.setDate(required.getDate()+7);
    let created=0;
    lowStock.forEach((part,index)=>{
      const quantity=Math.max(1,part.min-part.stock);
      const poNumber=`AUTO-${String(now.getFullYear()).slice(-2)}${String(now.getMonth()+1).padStart(2,'0')}${String(now.getDate()).padStart(2,'0')}-${String(Date.now()+index).slice(-4)}`;
      const po={poNumber,product:part.name,sku:part.sku,supplier:part.supplier,quantity,unitPrice:part.price,total:quantity*part.price,created:displayDate(now),requiredBy:displayDate(required),automatic:true};
      records.unshift(po);
      orders.unshift([po.poNumber,po.supplier,po.created,po.requiredBy,'1',formatMoney(po.total),'pending','Pending approval',po.product]);
      created++;
    });
    writeRecords(records);renderOrders();updateOrderMetrics();
    if(typeof showToast==='function')showToast(created?'Automatic POs created':'No low-stock products',created?`${created} low-stock purchase order${created===1?' is':'s are'} pending approval.`:'All products are currently at or above their reorder points.');
    if(typeof navigate==='function')navigate('orders');
  });

  updateOrderMetrics();
})();
